// This file is auto-generated by scripts/generate-questions.ts
// Sources: D:/Big Five Persona/questions.csv, D:/Big Five Persona/questions.ar.csv, D:/Big Five Persona/questions.ar-EG.csv
// Do not edit manually.

export const questions = [
  {
    "id": 1,
    "trait": "E",
    "key": 1,
    "code": "EXT1",
    "text": {
      "en": "I am the life of the party.",
      "ar": "أنا روح الحفل.",
      "ar-EG": "أنا روح القعدة."
    }
  },
  {
    "id": 2,
    "trait": "E",
    "key": -1,
    "code": "EXT2",
    "text": {
      "en": "I don't talk a lot.",
      "ar": "لا أتحدث كثيرًا.",
      "ar-EG": "مش بتكلم كتير."
    }
  },
  {
    "id": 3,
    "trait": "E",
    "key": 1,
    "code": "EXT3",
    "text": {
      "en": "I feel comfortable around people.",
      "ar": "أشعر بالراحة عندما أكون بين الناس.",
      "ar-EG": "بكون مرتاح وسط الناس."
    }
  },
  {
    "id": 4,
    "trait": "E",
    "key": -1,
    "code": "EXT4",
    "text": {
      "en": "I keep in the background.",
      "ar": "أفضل البقاء في الخلف.",
      "ar-EG": "بحب أبقى على جنب ومش ظاهر."
    }
  },
  {
    "id": 5,
    "trait": "E",
    "key": 1,
    "code": "EXT5",
    "text": {
      "en": "I start conversations.",
      "ar": "أبدأ المحادثات.",
      "ar-EG": "أنا اللي بفتح كلام."
    }
  },
  {
    "id": 6,
    "trait": "E",
    "key": -1,
    "code": "EXT6",
    "text": {
      "en": "I have little to say.",
      "ar": "ليس لدي الكثير لأقوله.",
      "ar-EG": "مبقاش عندي كلام كتير أقوله."
    }
  },
  {
    "id": 7,
    "trait": "E",
    "key": 1,
    "code": "EXT7",
    "text": {
      "en": "I talk to a lot of different people at parties.",
      "ar": "أتحدث مع كثير من الأشخاص المختلفين في الحفلات.",
      "ar-EG": "بتكلم مع ناس كتير مختلفة في الحفلات."
    }
  },
  {
    "id": 8,
    "trait": "E",
    "key": -1,
    "code": "EXT8",
    "text": {
      "en": "I don't like to draw attention to myself.",
      "ar": "لا أحب أن ألفت الانتباه إلى نفسي.",
      "ar-EG": "مبحبش ألفت النظر لنفسي."
    }
  },
  {
    "id": 9,
    "trait": "E",
    "key": 1,
    "code": "EXT9",
    "text": {
      "en": "I am skilled in handling social situations.",
      "ar": "أجيد التعامل مع المواقف الاجتماعية.",
      "ar-EG": "بعرف أتعامل كويس في المواقف الاجتماعية."
    }
  },
  {
    "id": 10,
    "trait": "E",
    "key": -1,
    "code": "EXT10",
    "text": {
      "en": "I am quiet around strangers.",
      "ar": "أكون هادئًا مع الغرباء.",
      "ar-EG": "ببقى هادي مع الناس اللي معرفهمش."
    }
  },
  {
    "id": 11,
    "trait": "N",
    "key": -1,
    "code": "EST1",
    "text": {
      "en": "I get stressed out easily.",
      "ar": "أتوتّر بسهولة.",
      "ar-EG": "بتوتر بسرعة."
    }
  },
  {
    "id": 12,
    "trait": "N",
    "key": 1,
    "code": "EST2",
    "text": {
      "en": "I am relaxed most of the time.",
      "ar": "أكون مسترخياً معظم الوقت.",
      "ar-EG": "أنا رايق أغلب الوقت."
    }
  },
  {
    "id": 13,
    "trait": "N",
    "key": -1,
    "code": "EST3",
    "text": {
      "en": "I worry about things.",
      "ar": "أقلق بشأن الأمور.",
      "ar-EG": "بقلق على حاجات كتير."
    }
  },
  {
    "id": 14,
    "trait": "N",
    "key": 1,
    "code": "EST4",
    "text": {
      "en": "I seldom feel blue.",
      "ar": "نادراً ما أشعر بالحزن.",
      "ar-EG": "نادر لما أحس بزعل."
    }
  },
  {
    "id": 15,
    "trait": "N",
    "key": -1,
    "code": "EST5",
    "text": {
      "en": "I get nervous easily.",
      "ar": "أشعر بالتوتر بسهولة.",
      "ar-EG": "بتشد أعصابي بسهولة."
    }
  },
  {
    "id": 16,
    "trait": "N",
    "key": 1,
    "code": "EST6",
    "text": {
      "en": "I handle stress well.",
      "ar": "أتعامل مع الضغط النفسي جيدًا.",
      "ar-EG": "بعرف أتعامل مع الضغط كويس."
    }
  },
  {
    "id": 17,
    "trait": "N",
    "key": -1,
    "code": "EST7",
    "text": {
      "en": "I am easily disturbed.",
      "ar": "أنزعج بسهولة.",
      "ar-EG": "بتضايق بسرعة."
    }
  },
  {
    "id": 18,
    "trait": "N",
    "key": 1,
    "code": "EST8",
    "text": {
      "en": "I remain calm in difficult situations.",
      "ar": "أظل هادئًا في المواقف الصعبة.",
      "ar-EG": "بفضل هادي في المواقف الصعبة."
    }
  },
  {
    "id": 19,
    "trait": "N",
    "key": -1,
    "code": "EST9",
    "text": {
      "en": "I get upset easily.",
      "ar": "أنفعل بسهولة.",
      "ar-EG": "بتعصب بسهولة."
    }
  },
  {
    "id": 20,
    "trait": "N",
    "key": 1,
    "code": "EST10",
    "text": {
      "en": "I feel secure and stable.",
      "ar": "أشعر بالأمان والاستقرار.",
      "ar-EG": "حاسس بالأمان والاستقرار."
    }
  },
  {
    "id": 21,
    "trait": "A",
    "key": 1,
    "code": "AGR1",
    "text": {
      "en": "I am interested in people.",
      "ar": "أهتم بالناس.",
      "ar-EG": "بهتم بالناس."
    }
  },
  {
    "id": 22,
    "trait": "A",
    "key": -1,
    "code": "AGR2",
    "text": {
      "en": "I insult people.",
      "ar": "أهين الناس.",
      "ar-EG": "بجرح الناس بكلامي."
    }
  },
  {
    "id": 23,
    "trait": "A",
    "key": 1,
    "code": "AGR3",
    "text": {
      "en": "I sympathize with others' feelings.",
      "ar": "أتعاطف مع مشاعر الآخرين.",
      "ar-EG": "بتعاطف مع مشاعر غيري."
    }
  },
  {
    "id": 24,
    "trait": "A",
    "key": -1,
    "code": "AGR4",
    "text": {
      "en": "I am not really interested in others.",
      "ar": "لست مهتمًا حقًا بالآخرين.",
      "ar-EG": "مش مهتم قوي بالناس."
    }
  },
  {
    "id": 25,
    "trait": "A",
    "key": 1,
    "code": "AGR5",
    "text": {
      "en": "I have a soft heart.",
      "ar": "قلبي رقيق.",
      "ar-EG": "قلبي طيب."
    }
  },
  {
    "id": 26,
    "trait": "A",
    "key": -1,
    "code": "AGR6",
    "text": {
      "en": "I am not interested in other people's problems.",
      "ar": "لا أهتم بمشاكل الآخرين.",
      "ar-EG": "مش بهتم بمشاكل غيري."
    }
  },
  {
    "id": 27,
    "trait": "A",
    "key": 1,
    "code": "AGR7",
    "text": {
      "en": "I take time out for others.",
      "ar": "أخصص وقتًا للآخرين.",
      "ar-EG": "بلاقي وقت للناس."
    }
  },
  {
    "id": 28,
    "trait": "A",
    "key": -1,
    "code": "AGR8",
    "text": {
      "en": "I feel little concern for others.",
      "ar": "لا أشعر بقلق كبير تجاه الآخرين.",
      "ar-EG": "مش بقلق قوي على غيري."
    }
  },
  {
    "id": 29,
    "trait": "A",
    "key": 1,
    "code": "AGR9",
    "text": {
      "en": "I make people feel at ease.",
      "ar": "أجعل الناس يشعرون بالارتياح.",
      "ar-EG": "بخلي الناس ترتاح في الكلام معايا."
    }
  },
  {
    "id": 30,
    "trait": "A",
    "key": -1,
    "code": "AGR10",
    "text": {
      "en": "I am hard to get to know.",
      "ar": "يصعب على الناس التعرّف عليّ.",
      "ar-EG": "صعب الناس تعرفني كويس."
    }
  },
  {
    "id": 31,
    "trait": "C",
    "key": 1,
    "code": "CSN1",
    "text": {
      "en": "I am always prepared.",
      "ar": "أنا دائمًا مستعد.",
      "ar-EG": "دايمًا جاهز."
    }
  },
  {
    "id": 32,
    "trait": "C",
    "key": -1,
    "code": "CSN2",
    "text": {
      "en": "I leave my belongings around.",
      "ar": "أترك أغراضي مبعثرة.",
      "ar-EG": "بسيب حاجتي مرمية في كل حتة."
    }
  },
  {
    "id": 33,
    "trait": "C",
    "key": 1,
    "code": "CSN3",
    "text": {
      "en": "I pay attention to details.",
      "ar": "أنتبه للتفاصيل.",
      "ar-EG": "بركز في التفاصيل."
    }
  },
  {
    "id": 34,
    "trait": "C",
    "key": -1,
    "code": "CSN4",
    "text": {
      "en": "I make a mess of things.",
      "ar": "أجعل الأمور فوضوية.",
      "ar-EG": "بكركب الدنيا وبعمل لخبطة."
    }
  },
  {
    "id": 35,
    "trait": "C",
    "key": 1,
    "code": "CSN5",
    "text": {
      "en": "I get chores done right away.",
      "ar": "أنجز الأعمال والمهام فورًا.",
      "ar-EG": "بخلص اللي ورايا على طول."
    }
  },
  {
    "id": 36,
    "trait": "C",
    "key": -1,
    "code": "CSN6",
    "text": {
      "en": "I often forget to put things back in their proper place.",
      "ar": "غالبًا ما أنسى إعادة الأشياء إلى مكانها الصحيح.",
      "ar-EG": "كتير بنسى أرجّع الحاجة مكانها."
    }
  },
  {
    "id": 37,
    "trait": "C",
    "key": 1,
    "code": "CSN7",
    "text": {
      "en": "I like order.",
      "ar": "أحب النظام.",
      "ar-EG": "بحب النظام والترتيب."
    }
  },
  {
    "id": 38,
    "trait": "C",
    "key": -1,
    "code": "CSN8",
    "text": {
      "en": "I shirk my duties.",
      "ar": "أتهرب من واجباتي.",
      "ar-EG": "بتهرب من واجباتي."
    }
  },
  {
    "id": 39,
    "trait": "C",
    "key": 1,
    "code": "CSN9",
    "text": {
      "en": "I follow a schedule.",
      "ar": "أتبع جدولًا.",
      "ar-EG": "بمشي على جدول."
    }
  },
  {
    "id": 40,
    "trait": "C",
    "key": -1,
    "code": "CSN10",
    "text": {
      "en": "I am not a very detail-oriented person.",
      "ar": "لست شخصًا يهتم كثيرًا بالتفاصيل.",
      "ar-EG": "مش بتركز قوي في التفاصيل."
    }
  },
  {
    "id": 41,
    "trait": "O",
    "key": 1,
    "code": "OPN1",
    "text": {
      "en": "I have a vivid imagination.",
      "ar": "لدي خيال خصب.",
      "ar-EG": "خيالي واسع."
    }
  },
  {
    "id": 42,
    "trait": "O",
    "key": -1,
    "code": "OPN2",
    "text": {
      "en": "I have difficulty understanding abstract ideas.",
      "ar": "أواجه صعوبة في فهم الأفكار المجردة.",
      "ar-EG": "بلاقي صعوبة أفهم الأفكار المجردة."
    }
  },
  {
    "id": 43,
    "trait": "O",
    "key": 1,
    "code": "OPN3",
    "text": {
      "en": "I am quick to understand things.",
      "ar": "أفهم الأشياء بسرعة.",
      "ar-EG": "بفهم بسرعة."
    }
  },
  {
    "id": 44,
    "trait": "O",
    "key": -1,
    "code": "OPN4",
    "text": {
      "en": "I do not have a good imagination.",
      "ar": "ليس لدي خيال جيد.",
      "ar-EG": "خيالي مش قوي."
    }
  },
  {
    "id": 45,
    "trait": "O",
    "key": 1,
    "code": "OPN5",
    "text": {
      "en": "I enjoy reflecting on things.",
      "ar": "أستمتع بالتفكير والتأمل في الأمور.",
      "ar-EG": "بحب أقعد أفكر وأتأمل في الحاجات."
    }
  },
  {
    "id": 46,
    "trait": "O",
    "key": -1,
    "code": "OPN6",
    "text": {
      "en": "I avoid philosophical discussions.",
      "ar": "أتجنب النقاشات الفلسفية.",
      "ar-EG": "بتجنب النقاشات الفلسفية."
    }
  },
  {
    "id": 47,
    "trait": "O",
    "key": 1,
    "code": "OPN7",
    "text": {
      "en": "I am full of ideas.",
      "ar": "أنا مليء بالأفكار.",
      "ar-EG": "عندي أفكار كتير."
    }
  },
  {
    "id": 48,
    "trait": "O",
    "key": -1,
    "code": "OPN8",
    "text": {
      "en": "I seldom look for deeper meaning in things.",
      "ar": "نادراً ما أبحث عن المعنى الأعمق في الأشياء.",
      "ar-EG": "نادر لما أدور على معنى أعمق في الحاجات."
    }
  },
  {
    "id": 49,
    "trait": "O",
    "key": 1,
    "code": "OPN9",
    "text": {
      "en": "I enjoy thinking about theoretical ideas.",
      "ar": "أستمتع بالتفكير في الأفكار النظرية.",
      "ar-EG": "بحب أفكر في أفكار نظرية."
    }
  },
  {
    "id": 50,
    "trait": "O",
    "key": -1,
    "code": "OPN10",
    "text": {
      "en": "I am not interested in abstract ideas.",
      "ar": "لست مهتمًا بالأفكار المجردة.",
      "ar-EG": "مش مهتم بالأفكار المجردة."
    }
  }
] as const;
